angular.module('eShopApp').constant('events',{
  message:{

    _SHOW_BODY_SHADOW_:'_SHOW_BODY_SHADOW_',
    _HIDE_BODY_SHADOW_:'_HIDE_BODY_SHADOW_',
    _SHOW_MODAL_FORM_:'_SHOW_MODAL_FORM_',
    _HIDE_MODAL_FORM_:'_HIDE_MODAL_FORM_',
    _GET_PRODUCTS_:'_GET_PRODUCTS_',
    _GET_PRODUCTS_COMPLETE_:'_GET_PRODUCTS_COMPLETE_',
    _GET_PRODUCTS_FAILED_:'_GET_PRODUCTS_FAILED_',
    _ADD_ERROR_MESSAGE_:'_ADD_ERROR_MESSAGE_',
    _START_SERVER_REQUEST_:'_START_SERVER_REQUEST_',
    _END_SERVER_REQUEST_:'_END_SERVER_REQUEST_',
    _GET_PRODUCT_BY_ID_:'_GET_PRODUCT_BY_ID_',
    _GET_PRODUCT_BY_ID_COMPLETE_:'_GET_PRODUCT_BY_ID_COMPLETE_',
    _GET_PRODUCT_BY_ID_FAILED_:'_GET_PRODUCT_BY_ID_FAILED_',
    _GET_USER_BY_EMAIL_:'_GET_USER_BY_EMAIL_',
    _GET_USER_BY_EMAIL_COMPLETE_:'_GET_USER_BY_EMAIL_COMPLETE_',
    _GET_USER_BY_EMAIL_FAILED_:'_GET_USER_BY_EMAIL_FAILED_',
    _AUTHENTICATE_USER_BY_EMAIL_:'_AUTHENTICATE_USER_BY_EMAIL_',
    _AUTHENTICATE_USER_COMPLETE_:'_AUTHENTICATE_USER_COMPLETE_',
    _CREATE_USER_COMPLETE_:'_CREATE_USER_COMPLETE_',
    _CREATE_USER_FAILED_:'_CREATE_USER_FAILED_',
    _CREATE_USER_:'_CREATE_USER_',
    _RENDER_GOODS_:'_RENDER_GOODS_',

    //Cart
    _ADD_TO_CART_:'_ADD_TO_CART_',
    _REMOVE_FROM_CART_:'_REMOVE_FROM_CART_',
    _CLEAR_CART_:'_CLEAR_CART_',
    _SHOW_SHOPPING_CART_:'_SHOW_SHOPPING_CART_',
    _HIDE_SHOPPING_CART_:'_HIDE_SHOPPING_CART_',
    _GET_SHOPPING_CART_:'_GET_SHOPPING_CART_',

    ///Pagination
    _PAGINATION_GO_TO_FIRST_PAGE_:'_PAGINATION_GO_TO_FIRST_PAGE_',
    _PAGINATION_GO_TO_LAST_PAGE_:'_PAGINATION_GO_TO_LAST_PAGE_',
    _PAGINATION_GO_TO_NEXT_PAGE_:'_PAGINATION_GO_TO_NEXT_PAGE_',
    _PAGINATION_GO_TO_PREVIOUS_PAGE_:'_PAGINATION_GO_TO_PREVIOUS_PAGE_',
    _PAGINATION_SET_PAGE_:'_PAGINATION_SET_PAGE_',
    _PAGINATION_MOVE_:'_PAGINATION_MOVE_',

    //Search
    _SHOW_SEARCH_BODY_:'_SHOW_SEARCH_BODY_',
    _HIDE_SEARCH_BODY_:'_HIDE_SEARCH_BODY_',

    //Slider
    _SLIDER_INIT_STATE_:'_SLIDER_INIT_STATE_',
    _SLIDER_INIT_SUCCESS_:'_SLIDER_INIT_SUCCESS_',
    _SET_SLIDE_:'_SET_SLIDE_',
    _PREVIOUS_SLIDE_:'_PREVIOUS_SLIDE_',
    _NEXT_SLIDE_:'_NEXT_SLIDE_',
    _SLIDER_STATE_:'_SLIDER_STATE_'
  }
});
